version: '2'

services:
  web:
    build:
      context: .
      args:
        REQFILE: requirements-dev.txt
    container_name: insitu.app
    entrypoint: ["/usr/bin/tail", "-f", "/dev/null"]
    environment:
      - DJANGO_MIGRATE=yes
      - DJANGO_COLLECT_STATIC=yes
      - DJANGO_INDEX_CONTENT=no
      - UWSGI_PORT=8000
      - TIMEOUT=60
    depends_on:
      - db
    volumes:
      - static:/var/local/static
      - logging:/var/local/copernicus/logging

  db:
    image: postgres:15-alpine
    container_name: insitu.db
    command: postgres -c log_temp_files=300000
    env_file:
      - docker/db.env
    volumes:
      - data:/var/lib/postgresql/data

  elasticsearch_test:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: insitu.elasticsearch_test
    volumes:
      - esdata_test:/usr/share/elasticsearch/data
    ports:
      - 9201:9201

volumes:
  static:
    driver: local
  data:
    driver: local
  esdata_test:
    driver: local
  logging:
    driver: local
