# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DataGroup",
            new_name="Data",
        ),
        migrations.RenameField(
            model_name="datarequirement",
            old_name="data_group",
            new_name="data",
        ),
        migrations.RenameField(
            model_name="dataresponsiblerelation",
            old_name="data_group",
            new_name="data",
        ),
    ]
