# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picklists', '0003_essentialclimatevariable'),
        ('insitu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagroup',
            name='essential_climate_variables',
            field=models.ManyToManyField(to='picklists.EssentialClimateVariable'),
        ),
    ]
