# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insitu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataresponsible',
            name='members',
        ),
        migrations.AddField(
            model_name='dataresponsible',
            name='networks',
            field=models.ManyToManyField(blank=True, related_name='members', to='insitu.DataResponsible'),
        ),
        migrations.AlterField(
            model_name='dataresponsibledetails',
            name='data_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='insitu.DataResponsible'),
        ),
    ]
