# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insitu', '0003_requirement_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='end_time_coverage',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='start_time_coverage',
            field=models.DateField(null=True),
        ),
    ]
