# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insitu', '0003_auto_20170704_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagroup',
            name='_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datarequirement',
            name='_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataresponsible',
            name='_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataresponsibledetails',
            name='_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataresponsiblerelation',
            name='_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
