# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0005_link_dissemination_data"),
        ("picklists", "0003_responsibletype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataresponsibledetails",
            name="responsible_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="picklists.ResponsibleType",
            ),
        ),
    ]
