# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insitu', '0005_copernicusresponsible_countryresponsible'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='insitu.DataResponsible')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_resp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='copernicusresponsible',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_resp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='countryresponsible',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='country_resp', to=settings.AUTH_USER_MODEL),
        ),
    ]
