# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0006_add_responsible_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="quality",
            new_name="quality_control_procedure",
        ),
        migrations.RenameField(
            model_name="requirement",
            old_name="quality",
            new_name="quality_control_procedure",
        ),
    ]
