# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0007_rename_quality_picklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="acronym",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="copernicusservice",
            name="acronym",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="copernicusservice",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="copernicusservice",
            name="website",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dataresponsibledetails",
            name="acronym",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="dataresponsibledetails",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="dataresponsibledetails",
            name="contact_person",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="dataresponsibledetails",
            name="email",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="dataresponsibledetails",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="dataresponsibledetails",
            name="website",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="entrustedentity",
            name="acronym",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="entrustedentity",
            name="website",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="acronym",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
