# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insitu', '0008_remove_productrequirement_distance_to_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datagroup',
            old_name='essential_climate_variables',
            new_name='essential_variables',
        ),
    ]
