# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insitu', '0009_rename_essential_climate_variable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datagroup',
            old_name='frequency',
            new_name='update_frequency',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='frequency',
            new_name='update_frequency',
        ),
    ]
