# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 10:34
from __future__ import unicode_literals

from django.db import migrations

from django_fsm import FSMField


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0010_rename_responsible_to_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="state",
            field=FSMField(default="draft", max_length=50),
        ),
        migrations.AddField(
            model_name="dataprovider",
            name="state",
            field=FSMField(default="draft", max_length=50),
        ),
        migrations.AddField(
            model_name="dataproviderdetails",
            name="state",
            field=FSMField(default="draft", max_length=50),
        ),
        migrations.AddField(
            model_name="dataproviderrelation",
            name="state",
            field=FSMField(default="draft", max_length=50),
        ),
        migrations.AddField(
            model_name="datarequirement",
            name="state",
            field=FSMField(default="draft", max_length=50),
        ),
        migrations.AddField(
            model_name="metric",
            name="state",
            field=FSMField(default="draft", max_length=50),
        ),
        migrations.AddField(
            model_name="productrequirement",
            name="state",
            field=FSMField(default="draft", max_length=50),
        ),
        migrations.AddField(
            model_name="requirement",
            name="state",
            field=FSMField(default="draft", max_length=50),
        ),
    ]
