# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 10:34
from __future__ import unicode_literals

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0010_rename_responsible_to_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="state",
            field=django_xworkflows.models.StateField(
                max_length=16,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="draft",
                    name="ValidationWorkflow",
                    states=["draft", "ready", "valid", "changes"],
                ),
            ),
        ),
        migrations.AddField(
            model_name="dataprovider",
            name="state",
            field=django_xworkflows.models.StateField(
                max_length=16,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="draft",
                    name="ValidationWorkflow",
                    states=["draft", "ready", "valid", "changes"],
                ),
            ),
        ),
        migrations.AddField(
            model_name="dataproviderdetails",
            name="state",
            field=django_xworkflows.models.StateField(
                max_length=16,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="draft",
                    name="ValidationWorkflow",
                    states=["draft", "ready", "valid", "changes"],
                ),
            ),
        ),
        migrations.AddField(
            model_name="dataproviderrelation",
            name="state",
            field=django_xworkflows.models.StateField(
                max_length=16,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="draft",
                    name="ValidationWorkflow",
                    states=["draft", "ready", "valid", "changes"],
                ),
            ),
        ),
        migrations.AddField(
            model_name="datarequirement",
            name="state",
            field=django_xworkflows.models.StateField(
                max_length=16,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="draft",
                    name="ValidationWorkflow",
                    states=["draft", "ready", "valid", "changes"],
                ),
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="state",
            field=django_xworkflows.models.StateField(
                max_length=16,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="draft",
                    name="ValidationWorkflow",
                    states=["draft", "ready", "valid", "changes"],
                ),
            ),
        ),
        migrations.AddField(
            model_name="productrequirement",
            name="state",
            field=django_xworkflows.models.StateField(
                max_length=16,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="draft",
                    name="ValidationWorkflow",
                    states=["draft", "ready", "valid", "changes"],
                ),
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="state",
            field=django_xworkflows.models.StateField(
                max_length=16,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="draft",
                    name="ValidationWorkflow",
                    states=["draft", "ready", "valid", "changes"],
                ),
            ),
        ),
    ]
