# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0011_add_created_by"),
        ("insitu", "0011_add_state_fields"),
    ]

    operations = []
