# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0012_merge_20171027_1440"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="copernicusprovider",
            name="service",
        ),
        migrations.RemoveField(
            model_name="copernicusprovider",
            name="user",
        ),
        migrations.RemoveField(
            model_name="countryprovider",
            name="country",
        ),
        migrations.RemoveField(
            model_name="countryprovider",
            name="user",
        ),
        migrations.RemoveField(
            model_name="dataprovideruser",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="dataprovideruser",
            name="user",
        ),
        migrations.DeleteModel(
            name="CopernicusProvider",
        ),
        migrations.DeleteModel(
            name="CountryProvider",
        ),
        migrations.DeleteModel(
            name="DataProviderUser",
        ),
    ]
