# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insitu', '0013_auto_20171101_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
