# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 10:49
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Count

from insitu.models import (
    DataProviderRelation,
    DataRequirement,
    ProductRequirement,
)


def remove_product_requirement_duplicates(*args):
    objects = ProductRequirement.objects.values(
        'product_id',
        'requirement_id'
    ).annotate(count=Count('product_id')).order_by().filter(count__gt=1)
    for object in objects:
        ids = ProductRequirement.objects.filter(
                  product=object['product_id'],
                  requirement=object['requirement_id'])[1:]
        ProductRequirement.objects.filter(id__in=ids).update(_deleted=True)


def remove_data_provider_duplicates(*args):
    objects = DataProviderRelation.objects.values(
        'data_id',
        'provider_id'
    ).annotate(count=Count('data_id')).order_by().filter(count__gt=1)
    for object in objects:
        ids = DataProviderRelation.objects.filter(
                  data=object['data_id'],
                  provider=object['provider_id'])[1:]
        DataProviderRelation.objects.filter(id__in=ids).update(_deleted=True)


def remove_data_requirement_duplicates(*args):
    objects = DataRequirement.objects.values(
        'data_id',
        'requirement_id'
    ).annotate(count=Count('data_id')).order_by().filter(count__gt=1)
    for object in objects:
        ids = DataRequirement.objects.filter(
                  data=object['data_id'],
                  requirement=object['requirement_id'])[1:]
        DataRequirement.objects.filter(id__in=ids).update(_deleted=True)


class Migration(migrations.Migration):

    dependencies = [
        ('insitu', '0014_update_data_fields'),
    ]

    operations = [
        migrations.RunPython(remove_product_requirement_duplicates),
        migrations.RunPython(remove_data_provider_duplicates),
        migrations.RunPython(remove_data_requirement_duplicates),
    ]
