# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0015_remove_duplicated_associative_relations"),
        ("picklists", "0008_rename_policy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="policy",
            new_name="data_policy",
        ),
    ]
