# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0016_rename_policy"),
        ("picklists", "0009_rename_coverage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="coverage",
            new_name="area",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="coverage",
            new_name="area",
        ),
    ]
