# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-05 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insitu', '0018_remove_mandatory_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='copernicusservice',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='essential_variables',
            field=models.ManyToManyField(blank=True, to='picklists.EssentialVariable'),
        ),
        migrations.AlterField(
            model_name='data',
            name='inspire_themes',
            field=models.ManyToManyField(blank=True, to='picklists.InspireTheme'),
        ),
        migrations.AlterField(
            model_name='entrustedentity',
            name='acronym',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
