# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-06 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("insitu", "0018_remove_mandatory_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teammates",
                    models.ManyToManyField(
                        related_name="teams", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="data",
            name="essential_variables",
            field=models.ManyToManyField(blank=True, to="picklists.EssentialVariable"),
        ),
        migrations.AlterField(
            model_name="data",
            name="inspire_themes",
            field=models.ManyToManyField(blank=True, to="picklists.InspireTheme"),
        ),
    ]
