# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-16 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insitu', '0019_add_team_to_user'),
        ('insitu', '0019_update_data_provider_name'),
    ]

    operations = [
    ]
