# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-20 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("insitu", "0020_merge_20180316_1017"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="requests",
            field=models.ManyToManyField(
                related_name="requests", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
