# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-03 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0021_team_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="requests",
            field=models.ManyToManyField(
                blank=True, related_name="requests", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
