# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-09 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insitu', '0022_team_requests_field_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='acronym',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
