# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-23 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0027_add_owner_to_requirement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
