# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-25 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insitu', '0028_change_product_name_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
