# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-12-22 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0031_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="acronym",
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
