# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-03-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0032_extend_product_acronym"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataprovider",
            name="edmo",
            field=models.IntegerField(null=True),
        ),
    ]
