# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-02 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0033_dataprovider_edmo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataprovider",
            name="edmo",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
