# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-03-03 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0034_update_edmo_dataprovider"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="owner_history",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="dataprovider",
            name="owner_history",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="dataproviderdetails",
            name="owner_history",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="dataproviderrelation",
            name="owner_history",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="datarequirement",
            name="owner_history",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="metric",
            name="owner_history",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="productrequirement",
            name="owner_history",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="requirement",
            name="owner_history",
            field=models.TextField(default=""),
        ),
    ]
