# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-03-03 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0035_add_owner_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="picklists.Status",
            ),
        ),
    ]
