# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-03-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("picklists", "0010_auto_20200305_1553"),
        ("insitu", "0036_alter_status_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="picklists.Status",
            ),
        ),
    ]
