# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-01 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0037_requirement_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=10, null=True)),
                ("description", models.TextField(null=True)),
                ("current", models.BooleanField(default=False)),
                ("created_at", models.DateField(null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
