# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-27 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0038_add_changelog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metric",
            name="state",
        ),
    ]
