# Generated by Django 2.2.24 on 2022-06-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insitu', '0040_auto_20210614_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_date', models.DateTimeField(null=True)),
                ('user', models.CharField(max_length=20, null=True)),
                ('action', models.CharField(max_length=50, null=True)),
                ('target_type', models.CharField(max_length=20, null=True)),
                ('id_target', models.CharField(max_length=5, null=True)),
                ('extra', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
