# Generated by Django 2.2.24 on 2022-10-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0041_loggedaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loggedaction",
            name="action",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="loggedaction",
            name="extra",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="loggedaction",
            name="id_target",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="loggedaction",
            name="target_type",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="loggedaction",
            name="user",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
