# Generated by Django 2.2.24 on 2022-11-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0042_auto_20221018_0910"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedaction",
            name="target_note",
            field=models.TextField(blank=True),
        ),
    ]
