# Generated by Django 2.2.24 on 2022-11-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insitu', '0044_dataprovider_native_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='owner_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='owner_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataproviderdetails',
            name='owner_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataproviderrelation',
            name='owner_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='datarequirement',
            name='owner_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='metric',
            name='owner_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='owner_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='owner_history',
            field=models.TextField(blank=True, default=''),
        ),
    ]
