# Generated by Django 2.2.28 on 2023-08-16 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0045_auto_20221128_1210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="data_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="picklists.DataPolicy",
            ),
        ),
    ]
