# Generated by Django 2.2.28 on 2023-08-25 07:56

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0046_auto_20230824_0911"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="state",
            field=django_fsm.FSMField(default="draft", max_length=50),
        ),
        migrations.AlterField(
            model_name="dataprovider",
            name="state",
            field=django_fsm.FSMField(default="draft", max_length=50),
        ),
        migrations.AlterField(
            model_name="dataproviderdetails",
            name="state",
            field=django_fsm.FSMField(default="draft", max_length=50),
        ),
        migrations.AlterField(
            model_name="dataproviderrelation",
            name="state",
            field=django_fsm.FSMField(default="draft", max_length=50),
        ),
        migrations.AlterField(
            model_name="datarequirement",
            name="state",
            field=django_fsm.FSMField(default="draft", max_length=50),
        ),
        migrations.AlterField(
            model_name="productrequirement",
            name="state",
            field=django_fsm.FSMField(default="draft", max_length=50),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="state",
            field=django_fsm.FSMField(default="draft", max_length=50),
        ),
    ]
