# Generated by Django 3.2.20 on 2023-12-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0048_merge_20230831_0717"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["_deleted", "area"], name="insitu_prod__delete_946ea0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productrequirement",
            index=models.Index(
                fields=["_deleted"], name="insitu_prod__delete_136bbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requirement",
            index=models.Index(
                fields=["_deleted"], name="insitu_requ__delete_9c0553_idx"
            ),
        ),
    ]
