# Generated by Django 3.2.20 on 2023-12-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0049_auto_20231220_0917"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="data",
            index=models.Index(
                fields=["_deleted"], name="insitu_data__delete_9385a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataprovider",
            index=models.Index(
                fields=["_deleted"], name="insitu_data__delete_a22289_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataproviderdetails",
            index=models.Index(
                fields=["_deleted"], name="insitu_data__delete_25b8eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataproviderrelation",
            index=models.Index(
                fields=["_deleted"], name="insitu_data__delete_7957f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datarequirement",
            index=models.Index(
                fields=["_deleted"], name="insitu_data__delete_f10455_idx"
            ),
        ),
    ]
