# Generated by Django 3.2.23 on 2024-01-17 10:17

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0050_auto_20231220_0954"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50, null=True)),
                ("description", markdownx.models.MarkdownxField()),
                ("current", models.BooleanField(default=False)),
                ("created_at", models.DateField(null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name_plural": "deliveries",
            },
        ),
    ]
