# Generated by Django 3.2.23 on 2024-01-18 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0051_delivery"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Delivery",
            new_name="Release",
        ),
        migrations.AlterModelOptions(
            name="release",
            options={"verbose_name_plural": "releases"},
        ),
    ]
