# Generated by Django 3.2.23 on 2024-03-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picklists", "0013_alter_country_code"),
        ("insitu", "0052_auto_20240118_1006"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="essential_variables",
            field=models.ManyToManyField(blank=True, to="picklists.EssentialVariable"),
        ),
    ]
