# Generated by Django 3.2.23 on 2024-03-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insitu', '0054_remove_data_essential_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='copernicus_service_product',
            field=models.BooleanField(default=False),
        ),
    ]
