# Generated by Django 3.2.23 on 2024-04-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0055_data_copernicus_service_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="entrusted_entity",
        ),
        migrations.AddField(
            model_name="component",
            name="entrusted_entities",
            field=models.ManyToManyField(
                blank=True, related_name="components", to="insitu.EntrustedEntity"
            ),
        ),
    ]
