# Generated by Django 3.2.25 on 2025-12-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0056_auto_20240401_1449"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataproviderrelation",
            name="state",
        ),
        migrations.RemoveField(
            model_name="datarequirement",
            name="state",
        ),
        migrations.RemoveField(
            model_name="productrequirement",
            name="state",
        ),
    ]
