# Generated by Django 3.2.25 on 2025-12-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0057_auto_20251208_1131"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataproviderdetails",
            name="state",
        ),
    ]
