# Generated by Django 3.2.25 on 2025-12-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insitu", "0058_remove_dataproviderdetails_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="note",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="requirement",
            old_name="note",
            new_name="description",
        ),
    ]
