# Generated by Django 3.2.25 on 2025-12-09 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("insitu", "0059_auto_20251209_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="teammates",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
