# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barrier',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='compliancelevel',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='coverage',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'coverage'},
        ),
        migrations.AlterModelOptions(
            name='criticality',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'criticality'},
        ),
        migrations.AlterModelOptions(
            name='dataformat',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='datatype',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='definitionlevel',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='dissemination',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'dissemination'},
        ),
        migrations.AlterModelOptions(
            name='frequency',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'frequency'},
        ),
        migrations.AlterModelOptions(
            name='inspiretheme',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'policy'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='productstatus',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'product status'},
        ),
        migrations.AlterModelOptions(
            name='quality',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'quality'},
        ),
        migrations.AlterModelOptions(
            name='relevance',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'relevance'},
        ),
        migrations.AlterModelOptions(
            name='targetdistance',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'target distance'},
        ),
        migrations.AlterModelOptions(
            name='timeliness',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'timeliness'},
        ),
    ]
