# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picklists', '0004_rename_quality_picklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponsibleType',
            new_name='ProviderType',
        ),
    ]
