# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picklists", "0005_rename_responsible_to_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="essentialvariable",
            name="component",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="essentialvariable",
            name="domain",
            field=models.CharField(max_length=100),
        ),
    ]
