# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picklists', '0006_rename_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancelevel',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coverage',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='criticality',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dataformat',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datatype',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='definitionlevel',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dissemination',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='essentialvariable',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspiretheme',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='policy',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productstatus',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quality',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='relevance',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='timeliness',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='updatefrequency',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
