# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picklists", "0006_change_esential_variable_choices_to_char"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productstatus",
            name="link",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
