# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picklists', '0007_increse_product_status_link_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Policy',
            new_name='DataPolicy',
        ),
        migrations.AlterModelOptions(
            name='datapolicy',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Data policies'},
        ),
    ]
