# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("picklists", "0008_rename_policy"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Coverage",
            new_name="Area",
        ),
        migrations.AlterModelOptions(
            name="area",
            options={"ordering": ["sort_order"], "verbose_name_plural": "areas"},
        ),
    ]
