# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-31 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picklists', '0010_auto_20180131_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissemination',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='qualitycontrolprocedure',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
