# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-05 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picklists', '0012_auto_20180205_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providertype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
