# Generated by Django 2.2.28 on 2023-08-30 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("use_cases", "0004_auto_20230830_0729"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="use_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="use_cases.UseCase"
            ),
        ),
    ]
