# Generated by Django 3.2.20 on 2023-09-04 10:26

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("use_cases", "0005_auto_20230830_1114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usecase",
            name="state",
            field=django_fsm.FSMField(default="draft", max_length=50),
        ),
    ]
