# Generated by Django 3.2.20 on 2023-09-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("use_cases", "0006_alter_usecase_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="feedback",
            field=models.TextField(blank=True),
        ),
    ]
