# Generated by Django 3.2.20 on 2023-09-05 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("use_cases", "0007_usecase_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usecase",
            old_name="submitted_by",
            new_name="created_by",
        ),
    ]
