# Generated by Django 3.2.20 on 2023-09-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("use_cases", "0008_rename_submitted_by_usecase_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usecase",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="usecase",
            name="image_description",
            field=models.TextField(null=True),
        ),
    ]
