# Generated by Django 3.2.20 on 2023-11-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use_cases', '0010_auto_20231128_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='data_provider',
        ),
    ]
