# Generated by Django 3.2.20 on 2023-11-28 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("use_cases", "0011_remove_usecase_data_provider"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usecase",
            old_name="data_provider_link",
            new_name="data_provider",
        ),
    ]
