# Generated by Django 3.2.20 on 2023-12-15 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0048_merge_20230831_0717"),
        ("use_cases", "0012_rename_data_provider_link_usecase_data_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usecase",
            name="copernicus_services",
        ),
        migrations.AddField(
            model_name="usecase",
            name="copernicus_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="insitu.copernicusservice",
            ),
        ),
    ]
