# Generated by Django 3.2.20 on 2023-12-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insitu", "0049_auto_20231220_0917"),
        ("use_cases", "0013_auto_20231215_1357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usecase",
            name="components",
            field=models.ManyToManyField(blank=True, null=True, to="insitu.Component"),
        ),
    ]
