# Generated by Django 3.2.20 on 2023-12-20 14:00

from django.db import migrations
import django_advance_thumbnail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("use_cases", "0014_alter_usecase_components"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="thumbnail",
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(
                blank=True, null=True, upload_to="use-case-images/"
            ),
        ),
    ]
